name: sphinx
channels:
  - conda-forge
dependencies:
  - python
  - sphinx
  - sphinx-intl
  - sphinx-copybutton
  - sphinx-design
  - sphinx-jinja 2.*
  - sphinx-book-theme 0.2
  - ablog
  - myst-parser
